# Add Catppucin Theme
import = [
  "~/.config/alacritty/themes/catppuccin_macchiato.toml"
]

# Switch to Meslo Nerd Font
[font]
size = 12.0
[font.normal]
family = "MesloLGS NF"
style = "Regular"
[font.bold]
family = "MesloLGS NF"
style = "Bold"
[font.italic]
family = "MesloLGS NF"
style = "Italic"
[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

