# Add Catppucin Theme
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

# Switch to Meslo Nerd Font
[font]
[font.normal]
family = "MesloLGS NF"
style = "Regular"
[font.bold]
family = "MesloLGS NF"
style = "Bold"
[font.italic]
family = "MesloLGS NF"
style = "Italic"
[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

